/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/forms/Footer.vue')['default']
    ForgotPassword: typeof import('./components/forms/ForgotPassword.vue')['default']
    Header: typeof import('./components/forms/Header.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    LoginUser: typeof import('./components/forms/LoginUser.vue')['default']
    RegisterUser: typeof import('./components/forms/RegisterUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
